#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

# Zero free space to aid VM compression
echo "Zeroing free space. Reports 'No space left on device' when complete."
# dd exits with a 1 when the device is full, ignore since this is expected
dd if=/dev/zero of=/EMPTY bs=1M || true
rm -f /EMPTY

# Block until the empty file has been removed, otherwise, Packer
# will try to kill the box while the disk is still full and that's bad
sync
