# -*- mode: ruby -*-
# vi: set ft=ruby :

# Specify Vagrant version, Vagrant API version, and Vagrant clone location
Vagrant.require_version '>= 1.6.0'
VAGRANTFILE_API_VERSION = '2'

# Require 'yaml' module
require 'yaml'

# Read YAML file with VM details (box, CPU, and RAM)
machines = YAML.load_file(File.join(File.dirname(__FILE__), 'machines.yml'))

# Create and configure the VMs
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Always use Vagrant's default insecure key
  config.ssh.insert_key = false

  # Iterate through entries in YAML file to create VMs
  machines.each do |machine|
    config.vm.define machine['name'] do |srv|

      # Don't check for box updates
      srv.vm.box_check_update = false

      # Set VM hostname and Vagrant box to use (default to VMware box)
      srv.vm.hostname = machine['name']
      srv.vm.box = machine['vmw_box']

      # Disable default synced folder
      srv.vm.synced_folder '.', '/vagrant', disabled: true

      # If it exists, copy the rkt download into the Vagrant VM
      if File.file?(File.join(File.dirname(__FILE__), 'rkt-v1.20.0.tar.gz'))
        srv.vm.provision 'file', source: 'rkt-v1.20.0.tar.gz',
          destination: '/home/vagrant/rkt-v1.20.0.tar.gz'
      end # if File.file?(rkt)

      # Run the provisioning shell script
      srv.vm.provision 'shell', path: 'provision.sh'

      # Configure VMs with RAM and CPUs per machines.yml (Fusion)
      srv.vm.provider 'vmware_fusion' do |vmw|
        vmw.vmx['memsize'] = machine['ram']
        vmw.vmx['numvcpus'] = machine['vcpu']
      end # srv.vm.provider 'vmware_fusion'

      # Configure the VM with RAM and CPUs per machines.yml (VirtualBox)
      srv.vm.provider 'virtualbox' do |vb, override|
        vb.memory = machine['ram']
        vb.cpus = machine['vcpu']
        override.vm.box = machine['vb_box']
      end # srv.vm.provider 'virtualbox'
    end # config.vm.define
  end # machines.each
end # Vagrant.configure
