# -*- mode: ruby -*-
# vi: set ft=ruby :

# Specify Vagrant version, Vagrant API version, and Vagrant clone location
Vagrant.require_version '>= 1.6.0'
VAGRANTFILE_API_VERSION = '2'

# Create and configure the VM(s)
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Assign a friendly name to this host VM
  config.vm.hostname = 'docker-host'

  # Skip checking for an updated Vagrant box
  config.vm.box_check_update = false

  # Always use Vagrant's default insecure key
  config.ssh.insert_key = false

  # Spin up a 'host box' for use with the Docker provider
  # and then provision it with Docker
  config.vm.box = 'bento/ubuntu-14.04'
  config.vm.provision 'docker'

  # Kill SSH connection to Docker Host
  # Workaround for Vagrant issue #3998 related to group memberships
  config.vm.provision 'shell', inline: 'ps aux | grep 'sshd:' | awk '{print $2}' | xargs kill'

  # Disable synced folders (prevents an NFS error on 'vagrant up')
  config.vm.synced_folder '.', '/vagrant', disabled: true
end
