# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'json'

require './builder'

Vagrant.configure('2') do |config|

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = false
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  build(config, JSON.parse(File.read('config/provision.json')))
end
